<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-28 17:10
=======
# Generated by Django 5.2.1 on 2025-05-28 17:09
>>>>>>> twofactor

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_secret',
        ),
    ]
