# Generated by Django 5.0.7 on 2025-05-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_encryptedfile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='download_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
