# Generated by Django 5.0.7 on 2025-05-31 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_encryptedfile_download_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='download_limit',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='expires_at',
        ),
    ]
