# Generated by Django 5.0.7 on 2025-06-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_fileactivitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileActivityLog',
        ),
    ]
