# Generated by Django 5.2.1 on 2025-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_delete_fileactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
