# Generated by Django 5.2.1 on 2025-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_encryptedfile_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
