# Generated by Django 5.0.7 on 2025-06-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='download_counts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='vault.encryptedfile'),
            preserve_default=False,
        ),
    ]
