# Generated by Django 5.0.7 on 2025-06-05 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_userlog_download_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='download_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='download_counts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.encryptedfile'),
        ),
    ]
