# Generated by Django 5.2.1 on 2025-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_alter_encryptedfile_download_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='download_counts',
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('DELETE', 'Delete')], max_length=20),
        ),
    ]
