# Generated by Django 5.2.1 on 2025-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_remove_userlog_download_counts_alter_userlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
